apiVersion: v1
kind: Service
metadata:
  name: frontend-service-nodeport
spec:
  type: NodePort
  selector:
    type: web-app
  ports:
    - name: http
      port: 80
      targetPort: 80 # Vai para o web-server-apache pod.yaml
      # targetPort: 8080 # Vai para o web-server-tomcat pod.yaml
      nodePort: 30008
